### ISSUE TITLE
mixer.getvolume()[0] is negative 

### ISSUE THREAD

**Issue by willcode4food** [Fornoth/spotify-connect-web#62]
I'm trying to get this to run on one of those new fancy [C.H.I.P.](https://nextthing.co/pages/chip) computers .  And I am getting an error when running the chroot version 

  File "main.py", line 27, in <module>
    connect_app = Connect(web_error_callback)
  File "/usr/src/app/connect.py", line 75, in **init**
    lib.SpPlaybackUpdateVolume(mixer_volume)
OverflowError: can't convert negative number to unsigned

I can play audio files using aplayer specifying device hw:0,0 without issues.  For some reason, the mixer.getvolume() call is returning a negative value.  alsamixer allows me to toggle the volume without issue.   Any help would be appreciated.

**Comment by Fornoth** [comment]
If you're using the built in audio hardware, try passing `--playback_device 'default:CARD=sun4icodec' --mixer 'Power Amplifier'` as options

**Comment by willcode4food** [comment]
That worked!  Thanks!

**Comment by fightforlife** [comment]
I am sorry for reopening this, but I can not use the --mixer option because "Power Amplifier" has a space in it.

./spotify-connect-web.sh ...  --bitrate 320 --playback_device 'default:CARD=sun4icodec' --mixer 'Power Amplifier'

File "/usr/src/app/console_callbacks.py", line 28, in <module>
    mixer = alsa.Mixer(args.mixer)
alsaaudio.ALSAAudioError: Unable to find mixer control 'Power',0

**Comment by Fornoth** [comment]
@fightforlife try putting double quotes around `--mixer` itself, like `"--mixer 'Power Amplifier'"`
